package dev.vaijanath.chiefofstaff.agent;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.vaijanath.aiagent.model.Message;
import dev.vaijanath.aiagent.model.ModelResponse;
import dev.vaijanath.aiagent.model.StreamingModelPort;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;

/** Routing logic: auto-request short-circuit, structured routing, and specialist delegation. */
class SupervisorTest {

    private static final StreamingModelPort NO_STREAM = (req, onToken) -> {
        onToken.accept("");
        return ModelResponse.text("");
    };

    private Supervisor supervisor(Object route, String modelReply, Map<String, ChatAgent> specialists) {
        return new Supervisor(
                new TestDoubles.StubModel(modelReply),
                NO_STREAM,
                new TestDoubles.StubStructured(route),
                specialists);
    }

    @Test
    void autoGeneratedRequestReturnsEmptyList() {
        Supervisor s = supervisor(new Supervisor.Route("meta"), "META", Map.of());
        String out = s.respond(List.of(Message.user("{\"title\":\"Summary\"}"))).output();
        assertEquals("[]", out);
    }

    @Test
    void routesToMetaAndReformulates() {
        Supervisor s = supervisor(new Supervisor.Route("meta"), "META_REPLY", Map.of());
        assertEquals("META_REPLY", s.respond(List.of(Message.user("who are you?"))).output());
    }

    @Test
    void delegatesToSpecialist() {
        Map<String, ChatAgent> specialists = new LinkedHashMap<>();
        specialists.put("comms", new TestDoubles.StubChatAgent("COMMS_OUT"));
        Supervisor s = supervisor(new Supervisor.Route("comms"), "META", specialists);
        assertEquals("COMMS_OUT", s.respond(List.of(Message.user("draft an email"))).output());
    }

    @Test
    void unknownRouteFallsBackToMeta() {
        // Route returns a specialist id not present in the registry → supervisor answers meta itself.
        Map<String, ChatAgent> specialists = new LinkedHashMap<>();
        specialists.put("comms", new TestDoubles.StubChatAgent("COMMS_OUT"));
        Supervisor s = supervisor(new Supervisor.Route("nonexistent"), "META_REPLY", specialists);
        assertTrue(s.respond(List.of(Message.user("hello"))).output().contains("META_REPLY"));
    }

    @Test
    void routesToCreatorSpecialist() {
        Map<String, ChatAgent> specialists = new LinkedHashMap<>();
        specialists.put("creator", new TestDoubles.StubChatAgent("CREATOR_OUT"));
        specialists.put("comms", new TestDoubles.StubChatAgent("COMMS_OUT"));
        Supervisor s = supervisor(new Supervisor.Route("creator"), "META", specialists);
        assertEquals("CREATOR_OUT", s.respond(List.of(Message.user("make me a note on RAG"))).output());
    }
}
